[build]
dockerfilePath = "apps/signaling-server/Dockerfile"
context = "apps/signaling-server"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
