name: Build Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Debug Info
        run: echo "Workflow started!"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        working-directory: ./apps/web
        run: npm install --legacy-peer-deps

      - name: Create Env File
        working-directory: ./apps/web
        run: cp .env.example .env

      - name: Build Web App
        working-directory: ./apps/web
        run: npm run build

      - name: Sync Android Platform
        working-directory: ./apps/web
        run: npx cap sync android

      - name: Fix ProGuard Config
        working-directory: ./apps/web/android/app
        run: |
          sed -i 's/proguard-android.txt/proguard-android-optimize.txt/g' build.gradle

      - name: Build APK
        working-directory: ./apps/web/android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Rename APK
        working-directory: ./apps/web/android/app/build/outputs/apk/debug
        run: mv app-debug.apk SUSE-DF.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SUSE-DF-APK
          path: apps/web/android/app/build/outputs/apk/debug/SUSE-DF.apk
